version: '3.8'

services:
  sandbox:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'PYTHON_VARIANT' to pick a version: 3, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        PYTHON_VARIANT: 3.8-buster
        DBT_VERSION: 0.21.0
        DBT_PLUGINS: 'postgres'
        WORKSPACE: /workspace

    volumes:
      - ..:/workspace:cached
    env_file:
      - ../config/postgres/access.env
    init: true

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../config/postgres/access.env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: null
